// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beequpeheuimlbyenmzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZXF1cGVoZXVpbWxieWVubXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNDEwMzgsImV4cCI6MjA1OTgxNzAzOH0.tMieRW9JzECQK6kscMLZEkgUVe1_MwfCl9mlHxM04Ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);